// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCuvSN95A5Q8B9xbE5aF-5y8cnyZdWjiCc',
    appId: '1:1051651195680:web:3276fb8242d787fe6acd45',
    messagingSenderId: '1051651195680',
    projectId: 'coletablu-d98f4',
    authDomain: 'coletablu-d98f4.firebaseapp.com',
    storageBucket: 'coletablu-d98f4.firebasestorage.app',
    measurementId: 'G-96S77N2M6F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDYqb_9vYLtN5r8P6z7fUrJUWcUBw_-ifU',
    appId: '1:1051651195680:android:0f20817806af82d26acd45',
    messagingSenderId: '1051651195680',
    projectId: 'coletablu-d98f4',
    storageBucket: 'coletablu-d98f4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCjpw-flTEwL0SB1gYwtoiqCk_9_AWZIiU',
    appId: '1:1051651195680:ios:dc1d7f0e070b04456acd45',
    messagingSenderId: '1051651195680',
    projectId: 'coletablu-d98f4',
    storageBucket: 'coletablu-d98f4.firebasestorage.app',
    iosBundleId: 'com.example.coletablu',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCjpw-flTEwL0SB1gYwtoiqCk_9_AWZIiU',
    appId: '1:1051651195680:ios:dc1d7f0e070b04456acd45',
    messagingSenderId: '1051651195680',
    projectId: 'coletablu-d98f4',
    storageBucket: 'coletablu-d98f4.firebasestorage.app',
    iosBundleId: 'com.example.coletablu',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCuvSN95A5Q8B9xbE5aF-5y8cnyZdWjiCc',
    appId: '1:1051651195680:web:c448caca50ba5e946acd45',
    messagingSenderId: '1051651195680',
    projectId: 'coletablu-d98f4',
    authDomain: 'coletablu-d98f4.firebaseapp.com',
    storageBucket: 'coletablu-d98f4.firebasestorage.app',
    measurementId: 'G-KZLPTN0R88',
  );

}